services:

  flask:
    container_name: 'flask_container'
    build: .
    ports:
      - "5001:5001"
    command: /web/predict_flask.py
    volumes: 
      - ./resources/web:/web
      - ./models:/models
    networks: 
      - practica_creativa
  
  zookeeper:    
    image: wurstmeister/zookeeper
    container_name: 'zookeeper_container'
    networks:
      - practica_creativa
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    container_name: 'kafka-container'
    
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "flight_delay_classification_request:1:1"
      
    depends_on:
      - "zookeeper"
    networks:
      - practica_creativa
  

  mongo:
    image: mongo:4.4
    container_name: 'mongo-container'
    ports:
      - "27017:27017"
    networks:
      - practica_creativa
    volumes:
      - ./resources:/resources/db
      - ./data:/data

  mongo_seed:
    build: ./mongo-seed
    depends_on:
      - mongo
    networks:
      - practica_creativa
  
  spark-master:
    image: bitnami/spark:3.3.0
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==spark-master"
    volumes:    
      - ./flight_prediction:/flight-prediction
      - ./models:/models
    networks:
      - practica_creativa

  spark-worker:
    image: bitnami/spark:3.3.0
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==spark-master"
    command: bash -c "sleep 12 && spark-submit --class es.upm.dit.ging.predictor.MakePrediction \
      --master 'local[*]' \
      --packages org.mongodb.spark:mongo-spark-connector_2.12:10.1.1,org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.0 \
      --conf spark.kafka.bootstrap.servers=kafka:9092 \
      /flight_prediction/target/scala-2.12/flight_prediction_2.12-0.1.jar"
    volumes:
      - ./flight_prediction:/flight_prediction
      - ./models:/models
    networks:
      - practica_creativa

networks:
  practica_creativa:
